### ISSUE TITLE
How to start

### ISSUE THREAD

**Issue by chrisblossom** [cescoferraro/react-boil#2]
How do I start this project?

After ``yarn run dll && yarn run dev``:
```
ModuleNotFoundError: Module not found: Error: Can't resolve './product' in '/Users/chris/github/react-boil/app/components'
    at factoryCallback (/Users/chris/github/react-boil/node_modules/webpack/lib/Compilation.js:265:39)
    at factory (/Users/chris/github/react-boil/node_modules/webpack/lib/NormalModuleFactory.js:247:20)
    at resolver (/Users/chris/github/react-boil/node_modules/webpack/lib/NormalModuleFactory.js:65:21)
    at asyncLib.parallel.e (/Users/chris/github/react-boil/node_modules/webpack/lib/NormalModuleFactory.js:138:21)
    at /Users/chris/github/react-boil/node_modules/async/dist/async.js:3861:9
    at /Users/chris/github/react-boil/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/chris/github/react-boil/node_modules/async/dist/async.js:996:13)
    at /Users/chris/github/react-boil/node_modules/async/dist/async.js:906:16
    at /Users/chris/github/react-boil/node_modules/async/dist/async.js:3858:13
    at resolvers.normal.resolve (/Users/chris/github/react-boil/node_modules/webpack/lib/NormalModuleFactory.js:130:23)
    at onResolved (/Users/chris/github/react-boil/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
    at loggingCallbackWrapper (/Users/chris/github/react-boil/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/chris/github/react-boil/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/Users/chris/github/react-boil/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/chris/github/react-boil/node_modules/enhanced-resolve/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/Users/chris/github/react-boil/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
```

EDIT:
Also:
```js
    ERROR in [at-loader] ./server/helpers.tsx:4:16
        TS2664: Invalid module name in augmentation, module 'React' cannot be found.

    ERROR in [at-loader] ./server/helpers.tsx:5:41
        TS2304: Cannot find name 'DOMAttributes'.

    ERROR in [at-loader] ./server/helpers.tsx:21:21
        TS2339: Property 'as' does not exist on type 'HTMLProps<HTMLLinkElement>'.
```

**Comment by cescoferraro** [comment]
@chrisblossom 
maybe this helps with the also bit
https://github.com/cescoferraro/react-boil/commit/ecd6a86b6238752dedff10a32cbb8fd2ed227eeb
and this with the first issue
https://github.com/cescoferraro/react-boil/commit/ee06a96d807ac81801229ec4bdf0ec96c1751467
please pull it again

I have just cloned in another directory, and it worked!

**Comment by chrisblossom** [comment]
still getting

```
Error: [at-loader] ./server/helpers.tsx:4:16
    TS2664: Invalid module name in augmentation, module 'React' cannot be found.
    at emitError (/Users/chris/github/react-boil/node_modules/awesome-typescript-loader/src/instance.ts:446:41)
    at /Users/chris/github/react-boil/node_modules/awesome-typescript-loader/src/instance.ts:476:43
    at Array.forEach (native)
    at /Users/chris/github/react-boil/node_modules/awesome-typescript-loader/src/instance.ts:476:27
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by cescoferraro** [comment]
this is only required for the preload links 
I removed it now, please pull it again
https://github.com/cescoferraro/react-boil/commit/3daad7d7c6ac41ba4a75c38aa36d9df97e7a368c

**Comment by chrisblossom** [comment]
You are inlining the DLL script directly into the page source:

```html
...
</div></div></div><script id="dll">var vendor =
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/

...
```

btw it seems like there are a lot of issues with this repo. Getting some console.errors and the initial build takes an extremely long time.

**Comment by cescoferraro** [comment]
@chrisblossom I know, You can remove it. It wont make any diferrence.
What platform are you on? 
I am running OSX and the initial build usualy takes 35s.
What errors?

**Comment by chrisblossom** [comment]
Kind of got it working.

JS console:

```
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
EnvSendPing @ .lp?dframe=t&id=290749&pw=n54v15K4D3&ns=craigs-8e724:5
EnvDisconnect @ .lp?dframe=t&id=290749&pw=n54v15K4D3&ns=craigs-8e724:10
g.Tc @ main_cc42845….no_css.js:66147
g.bb @ main_cc42845….no_css.js:66148
(anonymous) @ main_cc42845….no_css.js:66145
fg.close @ main_cc42845….no_css.js:66151
d.onerror @ main_cc42845….no_css.js:66153

localhost/:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').
```

**Comment by chrisblossom** [comment]
If you look at the source of your development build, ``React`` is still included. Which is why the DLL plugin doesn't need to be loaded.

**Comment by cescoferraro** [comment]
@chrisblossom the deprecation thing is firebase's fault.
It only happens if you refresh the same page on the same tab.

TODO:I should not load the service worker on my development environment.

I dont get it. The source of the server or the client?
Are you saying I should use webpack externals?
How can I fix it?

**Comment by cescoferraro** [comment]
It seems that my dll build only exports a vendor variable. 
 I was expecting it to export the React object. 
Now it complains about react not being present.

**Comment by chrisblossom** [comment]
Remove [webpack.dll.js#L17](https://github.com/cescoferraro/react-boil/blob/0dd9439d38565f9b7f1a1f2baa405891613ecae9/webpack.dll.js#L17) and your DLL plugin will work as expected.

**Comment by cescoferraro** [comment]
@chrisblossom removing this line has the same behaviour of adding react as a external dep.
This makes sense. I removed the external and removed that line.  But still, my vendor.dll.js only exports a vendor variable like

```js
var vendor = ....
```

I was expecting it to set React to the window. 
I will clone yours starter to see how it outputs the dll variables

getting 
```
external "react"?3c62:1 Uncaught ReferenceError: react is not defined
    at Object.module.exports.version (external "react"?3c62:1)
    at __webpack_require__ (bootstrap c61662828c80cf1fc502?a04c:695)
```

**Comment by chrisblossom** [comment]
Do not set React as an external dep. You want the DLL plugin to handle that. The DLL plugin is working as expected exporting just ``vendor``.

**Comment by chrisblossom** [comment]
But do clone my repo and check out build times and rebuild times.

**Comment by chrisblossom** [comment]
I think you'll need to remove [chrisblossom/react-universal-starter/.npmrc#L1](https://github.com/chrisblossom/react-universal-starter/blob/b37033d6160df7d5f24226475b2bd7d863ad4dd1/.npmrc#L1) for it to work. Otherwise just run ``yarn run start``

**Comment by cescoferraro** [comment]
@chrisblossom typescript is slow. 
I am not setting it as external, ddl is handling this fine now by removing that line you have mentioned.
But the browser breaks because nobody is exporting react.

**Comment by chrisblossom** [comment]
You need to keep [server/html.tsx#L30-L33](https://github.com/cescoferraro/react-boil/blob/3daad7d7c6ac41ba4a75c38aa36d9df97e7a368c/server/html.tsx#L30-L33) included. DLL vendor file needs to be loaded on the client before any other webpack bundles.

**Comment by chrisblossom** [comment]
I do not think Typescript is THAT slow...especially for rebuilds. I would look into [using more dev-friendly source maps](https://webpack.js.org/configuration/devtool/), using [webpack-node-externals](https://github.com/chrisblossom/react-universal-starter/blob/44574e66759be7b30943d0fed1981b848ce44052/tools/webpack/server.js#L12-L18). And look into caching with https://github.com/s-panferov/awesome-typescript-loader

**Comment by cescoferraro** [comment]
@chrisblossom Got it!
I needed __dirname at dll and dll reference context
https://github.com/storybooks/storybook/issues/361

This really helped
https://github.com/s-panferov/awesome-typescript-loader#usecache-boolean-defaultfalse
Rebuilds are much faster! ~1.5s 

Thanks!!!!!!!!!!!!!

**Comment by cescoferraro** [comment]
@chrisblossom 
can you explain me the rationale behind not bundling @faceyspacey libs with nodeExternals?
